{
 "title": "Overview",
 "tags": [
  "base",
  "minetest"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance:",
    "query": "label_values(avg_lag, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "uptime{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Current Lag",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max_lag{instance=\"$instance\"}",
     "legendFormat": "Lag"
    }
   ]
  },
  {
   "title": "Average Lag",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_lag{instance=\"$instance\"}",
     "legendFormat": "Lag"
    }
   ]
  },
  {
   "title": "Players",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "player_count{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "About",
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "content": "\n# Public minetest monitoring server\n\n* [Forum topic](https://forum.minetest.net/viewtopic.php?f=14&t=22473)\n* [Github](https://github.com/thomasrudin-mt/monitoring)\n\n\n\n\n"
  },
  {
   "title": "Monitoring Mod",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "version_major{instance=\"$instance\"} + (version_minor{instance=\"$instance\"} / 100)",
     "legendFormat": "Version"
    }
   ]
  },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 } },
  {
   "title": "Ingame Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "floor(ingame_time{instance=\"$instance\"}/1000.0) + ((ingame_time{instance=\"$instance\"}/1000.0 % 1) / 100 * 60)"
    }
   ]
  },
  {
   "title": "Players",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "player_count{instance=\"$instance\"}",
     "legendFormat": "Players"
    }
   ]
  },
  {
   "title": "Craft/Place/Dig/Eat count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(dig_count{instance=\"$instance\"}[10s])",
     "legendFormat": "Digged"
    },
    {
     "expr": "irate(craft_count{instance=\"$instance\"}[10s])",
     "legendFormat": "Crafted"
    },
    {
     "expr": "irate(eat_count{instance=\"$instance\"}[10s])",
     "legendFormat": "Eaten"
    },
    {
     "expr": "irate(place_count{instance=\"$instance\"}[10s])",
     "legendFormat": "Placed"
    },
    {
     "expr": "irate(received_fields{instance=\"$instance\"}[10s])",
     "legendFormat": "Fields"
    }
   ]
  },
  {
   "title": "Lag",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_lag{instance=\"$instance\"}",
     "legendFormat": "Average"
    },
    {
     "expr": "min_lag{instance=\"$instance\"}",
     "legendFormat": "Min"
    },
    {
     "expr": "max_over_time( max_lag{instance=\"$instance\"} [$__interval] )",
     "legendFormat": "Max"
    },
    {
     "expr": "irate(mapgen_generated_count{instance=\"$instance\"}[10s])",
     "legendFormat": "Mapgen"
    }
   ]
  },
  {
   "title": "ABM/LBM/Nodetimer Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "max_over_time( ( irate( abm_time{instance=\"$instance\"}[15s] ) )[$__interval:3s] )",
     "legendFormat": "ABM"
    },
    {
     "expr": "max_over_time( ( irate( lbm_time{instance=\"$instance\"}[15s] ) )[$__interval:3s] )",
     "legendFormat": "LBM"
    },
    {
     "expr": "max_over_time( ( irate( nodetimer_time{instance=\"$instance\"}[15s] ) )[$__interval:3s] )",
     "legendFormat": "Nodetimer"
    },
    {
     "expr": "max_over_time( ( irate( globalstep_time{instance=\"$instance\"}[15s] ) )[$__interval:3s] )",
     "legendFormat": "Globalstep"
    }
   ]
  },
  {
   "title": "Forceloaded blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "forceload_blocks_count{instance=\"$instance\"}",
     "legendFormat": "Blocks"
    }
   ]
  },
  {
   "title": "Lua VM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "lua_mem_kb{instance=\"$instance\"}",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "lua_mem_max_kb{instance=\"$instance\"}",
     "legendFormat": "Max Memory"
    },
    {
     "expr": "lua_mem_min_kb{instance=\"$instance\"}",
     "legendFormat": "Min Memory"
    }
   ]
  }
 ]
}