name: test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: buckaroobanzay/mtt@main
      with:
        modname: monitoring
        enable_coverage: "true"
    - uses: coverallsapp/github-action@v1